package com.bank.bian.promotionalevents;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Promotional Events
 *
 * Business Area:      Sales and Service
 * Business Domain:    Marketing
 * Functional Pattern: Operate
 * Asset Type:         Promotional Event
 * Control Record:     Promotional Event Operating Session
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Promotional Events — BIAN Semantic API")
                .description("Service Domain 'Promotional Events' (Operate pattern) "
                        + "operating on the 'Promotional Event Operating Session' control record.")
                .version("0.1.0"));
    }
}
